#!/bin/bash
# A simple variable example

NONE='\033[00m'
RED='\033[01;31m'
GREEN='\033[01;32m'
YELLOW='\033[01;33m'
PURPLE='\033[01;35m'
CYAN='\033[01;36m'
WHITE='\033[01;37m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
hour=`date +%H`
if [ $hour -lt 12 ] # if hour is less than 12
then
echo ">>>>>>> Hello ${GREEN}$USER ${NONE}Good Morning <<<<<<<"
elif [ $hour -le 16 ] # if hour is less than equal to 16
then
echo -e ">>>>>>> Hello ${GREEN}$USER ${NONE}Good Afternoon <<<<<<<"
elif [ $hour -le 20 ] # if hour is less than equal to 20
then
echo ">>>>>>> Hello ${GREEN}$USER ${NONE}Good Evening <<<<<<<"
else
echo ">>>>>>> Hello ${GREEN}$USER ${NONE}Good Night <<<<<<<"
fi
echo -e "==========================================" ${CYAN}
printf '   __                           _ ___
  / /_____  ___ _      ______ _(_) (_)___
 / __/ __ \/ _ \ | /| / / __ `/ / / / __ \
/ /_/ /_/ /  __/ |/ |/ / /_/ / / / / / / /
\__/\____/\___/|__/|__/\__,_/_/_/_/_/ /_/

'
echo -e ${NONE} ${BOLD}
ncal
echo -e ${NONE} ${YELLOW}
echo -e "Hello $(pwd)" ${NONE}